/* Single source of truth for publications and timeline. See README.md. */
window.ACADEMIC_DATA={
publications:[
{id:"lunar-hyperspectral",title:"Connecting Meteorite Spectra to Lunar Surface Composition Using Hyperspectral Imaging and Machine Learning",authors:["Fatemeh Fazel Hesar","Mojtaba Raouf","Amirmohammad Chegeni","Peyman Soltani","Bernard Foing","Elias Chatzitheodoridis","Michiel J. A. de Dood","Fons J. Verbeek"],journal:"Universe",year:2026,volume:"12",pages:"93",doi:"10.3390/universe12040093",publisher:"https://www.mdpi.com/2218-1997/12/4/93",arxiv:"https://arxiv.org/abs/2603.24323"},
{id:"galaxy-kinematics",title:"Assessing Galaxy Rotation Kinematics: Insights from Convolutional Neural Networks on Velocity Variations",authors:["Amirmohammad Chegeni","Fatemeh Fazel Hesar","Mojtaba Raouf","Bernard Foing","Fons J. Verbeek"],journal:"Universe",year:2025,volume:"11",pages:"92",doi:"10.3390/universe11030092",publisher:"https://www.mdpi.com/2218-1997/11/3/92",arxiv:"https://arxiv.org/abs/2503.02622"},
{id:"strong-lenses",title:"Reducing false positives in strong lens detection through effective augmentation and ensemble learning",authors:["Samira Rezaei","Amirmohammad Chegeni","Bharath Chowdhary Nagam","J. P. McKean","Mitra Baratchi","Koen Kuijken","Léon V. E. Koopmans"],journal:"Monthly Notices of the Royal Astronomical Society",year:2025,volume:"538",pages:"1081–1095",doi:"10.1093/mnras/staf327",publisher:"https://academic.oup.com/mnras/article/538/2/1081/8038276",arxiv:"https://arxiv.org/abs/2502.14936"},
{id:"computer-vision",title:"Bridging gaps with computer vision: AI in (bio)medical imaging and astronomy",authors:["Samira Rezaei","Amirmohammad Chegeni","Amir Javadpour","Alireza Vafaei Sadr","Lu Cao","Huub J. A. Röttgering","Marius Staring"],journal:"Astronomy and Computing",year:2025,volume:"51",pages:"100921",doi:"10.1016/j.ascom.2024.100921",publisher:"https://doi.org/10.1016/j.ascom.2024.100921"},
{id:"clusternets",title:"Clusternets: a deep learning approach to probe clustering dark energy",authors:["Amirmohammad Chegeni","Farbod Hassani","Alireza Vafaei Sadr","Nima Khosravi","Martin Kunz"],journal:"Monthly Notices of the Royal Astronomical Society",year:2024,volume:"531",pages:"1534–1545",doi:"10.1093/mnras/stae1075",publisher:"https://academic.oup.com/mnras/article/531/1/1534/7682277",arxiv:"https://arxiv.org/abs/2308.03517",code:"https://github.com/AM-Chegeni/Clusternets"}],
timeline:[
{date:"2026-08-31",endDate:"2026-09-04",type:"service",title:"Local Organizing Committee — Astrophysics and Space Science in Marche III",institution:"University of Padova",location:"Jesi, Italy",description:"Local organizing committee member for the Big Bang, Big Stars, Big Computers meeting.",links:[{label:"Event",url:"https://indico.dfa.unipd.it/event/1698/"}],tags:["Cosmology","HPC"]},
{date:"2026-03",type:"publication",publicationId:"lunar-hyperspectral",tags:["Machine learning","Hyperspectral imaging"]},
{date:"2025-09-01",endDate:"2025-09-05",type:"talk",title:"ClusterNets: a deep learning approach to probe clustering dark energy",institution:"DarkMap — Mapping the Dark Universe",location:"Budapest, Hungary",description:"Conference talk on learning signatures of clustering dark energy from simulations.",links:[{label:"Contribution",url:"https://indico.global/event/14239/contributions/133469/"}],tags:["Cosmology","Deep learning"]},
{date:"2025-04-15",type:"talk",title:"Persistence Detection in Slew Dark Data Using Autoencoders",institution:"University of Padova / INFN",location:"Padova, Italy",description:"Presentation on Euclid NISP slew-dark calibration data.",links:[{label:"Slides",url:"https://agenda.infn.it/event/46801/contributions/263405/"}],tags:["Euclid","NISP","Autoencoders"]},
{date:"2025-04",type:"publication",publicationId:"strong-lenses",tags:["Strong lensing","Computer vision"]},{date:"2025-03",type:"publication",publicationId:"galaxy-kinematics",tags:["Galaxy kinematics","Explainable AI"]},{date:"2025-01",type:"publication",publicationId:"computer-vision",tags:["Computer vision","Interdisciplinary AI"]},
{date:"2025",endDate:null,type:"research",title:"Research Fellow — Euclid NISP calibration",institution:"University of Padova / INFN Padova",location:"Padova, Italy",description:"Calibration-product trend analysis, flat-field stability monitoring, and persistence/systematics studies.",links:[{label:"INFN activity report",url:"https://agenda.infn.it/event/48168/contributions/272866/"}],tags:["Euclid","NISP","Calibration"]},
{date:"2024-06",type:"publication",publicationId:"clusternets",tags:["Dark energy","Simulations","Machine learning"]},
{date:"2021",endDate:"2023",type:"education",title:"M.Sc. studies — Gravity and Cosmology",institution:"Shahid Beheshti University",location:"Tehran, Iran",description:"Cosmological simulations and machine-learning approaches to clustering dark energy.",links:[{label:"Related paper",url:"https://doi.org/10.1093/mnras/stae1075"}],tags:["Cosmology","Machine learning"]},
{date:"2021-11-03",endDate:"2021-11-05",type:"conference",title:"ICRANet–Isfahan Astronomy Meeting",institution:"ICRANet / Isfahan University of Technology",location:"Online / Isfahan",description:"Participant, affiliated with Shahid Beheshti University.",links:[{label:"Event",url:"https://indico.icranet.org/event/2/"}],tags:["Astronomy"]},
{date:"2021-04-27",endDate:"2021-04-29",type:"conference",title:"LISA Canada Workshop",institution:"LISA Canada",location:"Online",description:"Workshop participant and signatory to the meeting white paper.",links:[{label:"Event",url:"https://indico.triumf.ca/event/220/"}],tags:["Gravitational waves"]}]};
